### ISSUE TITLE
No work at all

### ISSUE THREAD

**Issue by pulsar14** [Danielshow/autoenv#12]
VSCODE: 1.93.1 on Win11

Installed the **autoenv plugin v1.0.3**  
Added manually (?) in the settings.json, as suggested, the following:

```
{
    "autoenv-filename": "sample-env",
    ...

}
```

What I see:
1) by right-clicking a line with a key=value pair the Context menu doesn't show any "Add Line to Env" as You mention in your README.MD but it's available in the "Command Palette"
2) I've manually created also empty files in the workspace root folder:
   .env
   .sample-env
   sample-env       <-- as suggested!

3) NOTHING! Your plugin does nothing.

**Steps:**  

_settings.json_:

```
{
    "autoenv-filename": "sample-env",
    "jupyter.notebookFileRoot": "${workspaceFolder}",
    "python.analysis.typeCheckingMode": "basic",
    "markdown.styles": [
    ....
}
```

In a file fake.txt there's a line:
     Key1 = "TEST"

Right click on that line --> open Command Palette --> click on "Add Line to Env" --> ??? nothing happens ... there's no line added to the sample-env, .env, .sample-env files.

And why I can't see this Extension in the Workspace Extensions list in the VSCode Settings as ALL others installed Settings?

Can You help me, please?

**Comment by Danielshow** [comment]
@pulsar14 It works for only Javascript files. I will still add support for typescript
change your file to fake.js and test
